*&---------------------------------------------------------------------*
*& Report ZPG_SMF1_RAILS
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZPG_SMF1_RAILS.

PARAMETERS: P_CUSTID TYPE SCUSTOM-ID OBLIGATORY.

DATA: IT_BOOKINGS     TYPE TABLE OF ZY0124SBO,
      WA_BOOKING      TYPE ZY0124SBO,
      IT_CUSTOMER     TYPE TABLE OF ZCUSTRAILS,
      WA_CUSTOMER     TYPE ZCUSTRAILS,
      IT_GROUPED_DATA TYPE ZTT_FLIGHT_GROUP_RAILS,
      WA_GROUP        TYPE ZST_FLIGHT_GROUP_RAILS.

DATA: LT_TEMP_TOTALS  TYPE TABLE OF ZST_TOTAL_AMOUNT_RAILS, " Bảng tạm tổng tiền
      LV_TOTAL_AMOUNT TYPE ZST_TOTAL_AMOUNT_RAILS.         " Một dòng tạm tổng tiền

DATA: IT_SMARTFORM_DATA TYPE TABLE OF ZY0124SBO.

START-OF-SELECTION.

  SELECT SINGLE * FROM ZCUSTRAILS INTO WA_CUSTOMER WHERE ID = P_CUSTID.
  IF SY-SUBRC <> 0.
    MESSAGE 'Customer not found' TYPE 'E'.
  ENDIF.

  SELECT * FROM ZY0124SBO INTO TABLE IT_BOOKINGS WHERE CUSTOMID = P_CUSTID.
  IF SY-SUBRC <> 0.
    MESSAGE 'No bookings found for the customer' TYPE 'I'.
  ENDIF.

  SORT IT_BOOKINGS BY CARRID.

  LOOP AT IT_BOOKINGS INTO WA_BOOKING.
    IF WA_GROUP-CARRIER_GROUP IS INITIAL OR WA_GROUP-CARRIER_GROUP <> WA_BOOKING-CARRID.

      IF WA_GROUP-CARRIER_GROUP IS NOT INITIAL.
        WA_GROUP-TOTAL_AMOUNT = LT_TEMP_TOTALS.
        APPEND WA_GROUP TO IT_GROUPED_DATA.
      ENDIF.

      CLEAR WA_GROUP.
      WA_GROUP-CARRIER_GROUP = WA_BOOKING-CARRID.
      CLEAR LT_TEMP_TOTALS.
    ENDIF.

    APPEND WA_BOOKING TO WA_GROUP-BOOKINGS.

    READ TABLE LT_TEMP_TOTALS WITH KEY FORCURKEY = WA_BOOKING-FORCURKEY
     ASSIGNING FIELD-SYMBOL(<FS_TEMP_TOTAL>).
    IF SY-SUBRC = 0.
      " Nếu đã tồn tại, sửa dòng hiện tại
      <FS_TEMP_TOTAL>-FORCURAM = <FS_TEMP_TOTAL>-FORCURAM + WA_BOOKING-FORCURAM.
    ELSE.
      " Nếu chưa tồn tại, thêm dòng mới
      CLEAR LV_TOTAL_AMOUNT.
      LV_TOTAL_AMOUNT-FORCURKEY = WA_BOOKING-FORCURKEY.
      LV_TOTAL_AMOUNT-FORCURAM = WA_BOOKING-FORCURAM.
      APPEND LV_TOTAL_AMOUNT TO LT_TEMP_TOTALS.
    ENDIF.
  ENDLOOP.

  IF WA_GROUP-CARRIER_GROUP IS NOT INITIAL.
    APPEND WA_GROUP TO IT_GROUPED_DATA.
  ENDIF.


  DATA: LV_FM_NAME            TYPE RS38L_FNAM.

  CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
    EXPORTING
      FORMNAME           = 'ZSF_SM_RAILS222'
    IMPORTING
      FM_NAME            = LV_FM_NAME
    EXCEPTIONS
      NO_FORM            = 1
      NO_FUNCTION_MODULE = 2
      OTHERS             = 3.

  IF SY-SUBRC <> 0.
    MESSAGE 'Smartform not found' TYPE 'E'.
    RETURN.
  ENDIF.

  CALL FUNCTION LV_FM_NAME
    EXPORTING
      SCUSTOM = WA_CUSTOMER
      SBOOK   = IT_GROUPED_DATA.
